[project]
name = "xtalk"
version = "0.0.1"
dependencies = [
    "Django",
    "django_htmx",
]

[project.optional-dependencies]
dev = [
    "django-browser-reload",
    "django-stubs",
    "pyright",
    "ruff-lsp",
]
